[toolchain]
anchor_version = "0.32.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pencil_solana = "G7XrbiCSkpBRyys2US19NLNf256Bm3BQ7okzDCWeuxzs"

[programs.localnet]
pencil_solana = "G7XrbiCSkpBRyys2US19NLNf256Bm3BQ7okzDCWeuxzs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "localnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.test.ts' 'tests/pencil-solana.ts'"
deploy = "yarn run scripts/deploy.ts"
configure = "yarn run scripts/configure.ts"
