[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pencil_solana = "RXo7Ai9ugeBp9giAKqera2pg1xMj49exA5SgWdMBMuM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "bun run scripts/deploy.ts"
configure = "bun run scripts/configure.ts"
